version: '3'
services:
  db:
    build: ./mySQL
    ports:
      - "3406:3406"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop